# Generated by Django 5.0 on 2023-12-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'killer_student'},
        ),
        migrations.AddField(
            model_name='contact',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
