# Generated by Django 5.0 on 2024-01-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_contact_options_contact_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
