# Generated by Django 5.0 on 2023-12-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
