# Generated by Django 5.0 on 2023-12-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('phon', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
