# Generated by Django 5.0 on 2023-12-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p6', '0006_students_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, default=1, upload_to='student/'),
            preserve_default=False,
        ),
    ]
