# Generated by Django 5.0 on 2023-12-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p6', '0007_alter_students_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('phon', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, upload_to='student/')),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
