# Generated by Django 5.0 on 2023-12-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new1app', '0004_alter_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='User',
            new_name='Users',
        ),
    ]
