# Generated by Django 5.0 on 2023-12-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new1app', '0005_rename_user_student_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Users',
        ),
    ]
