# Generated by Django 5.0 on 2023-12-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new1app', '0006_remove_student_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
