# Generated by Django 5.0 on 2023-12-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new1app', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
