# Generated by Django 5.0 on 2023-12-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1app', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
