# Generated by Django 5.0 on 2023-12-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentttt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.FileField(blank=True, upload_to='static/')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
