# Generated by Django 5.0 on 2023-12-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0002_studentttt_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentttt',
            name='photo',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
