# Generated by Django 5.0 on 2024-06-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_colors_student_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='color',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
    ]
