# Generated by Django 5.0 on 2023-12-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbankapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankusers',
            name='Account_type',
        ),
        migrations.AddField(
            model_name='bankusers',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'Savings Account'), ('Checking', 'Current Account'), ('Student', 'Student Account'), ('Business', 'Business Account'), ('Loan', 'Loan Account')], default=1, max_length=40),
            preserve_default=False,
        ),
    ]
