# Generated by Django 5.0 on 2024-01-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbankapp', '0003_cardapplication_helpdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardapplication',
            old_name='username',
            new_name='user',
        ),
    ]
