# Generated by Django 5.0 on 2024-01-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbankapp', '0005_loanrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpdata',
            name='user',
        ),
        migrations.AddField(
            model_name='helpdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
