# Generated by Django 5.0 on 2024-01-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbankapp', '0006_remove_helpdata_user_helpdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankusers',
            name='account_number',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='bankusers',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bankusers',
            name='interest_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankusers',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='Loan_Tenure',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='purpose',
            field=models.CharField(choices=[('home', 'Home Purchase'), ('Helth', 'Helth Loan'), ('car', 'Car Loan'), ('education', 'Education'), ('personal', 'Personal'), ('other', 'Other')], max_length=20),
        ),
    ]
