# Generated by Django 5.0 on 2024-01-03 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbankapp', '0007_bankusers_account_number_bankusers_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankusers',
            old_name='balance',
            new_name='current_balance',
        ),
        migrations.AlterField(
            model_name='bankusers',
            name='account_number',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Credited', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Debited', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Transferred', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emi', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bank_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbankapp.bankusers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
