# Generated by Django 5.0 on 2024-01-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbankapp', '0008_rename_balance_bankusers_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankusers',
            name='account_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
