# Generated by Django 5.0 on 2024-01-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbankapp', '0009_alter_bankusers_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankusers',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='bankusers',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Credited',
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Debited',
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='emi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
