# Generated by Django 5.0 on 2024-01-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbankapp', '0010_alter_bankusers_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Credited',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Debited',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transferred',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
