# Generated by Django 5.0 on 2024-01-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbankapp', '0011_alter_transaction_credited_alter_transaction_debited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Credited',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Debited',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
