# Generated by Django 5.0 on 2024-01-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbankapp', '0012_alter_transaction_credited_alter_transaction_debited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankusers',
            name='current_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bankusers',
            name='loan_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.FloatField(),
        ),
    ]
