# Generated by Django 4.2.1 on 2023-10-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('phon', models.BigIntegerField()),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
