# Generated by Django 5.0 on 2024-06-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapiapp', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
