# Generated by Django 5.0 on 2023-12-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0002_alter_contact_timestamp_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
