# Generated by Django 5.0 on 2023-12-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0004_alter_contact_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='lastname',
        ),
    ]
