# Generated by Django 5.0 on 2023-12-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0005_remove_contact_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='stname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
